spring.application.name=TrafficMirror

# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://root:AlWByEXUE7gvJNQg@cluster0.m4ffd8c.mongodb.net/edu_ai?retryWrites=true&w=majority&appName=Cluster0

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# CORS Configuration
spring.mvc.cors.allowed-origins=http://localhost:3000
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true

# Spring Security OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=63945279865-4nvs024iqj97ld2a11gun6ldkgucvv3d.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

